common:
  namespace: mateapp

global:
  ENVIRONMENT: "Development"

mysql:
  configs:
    MYSQL_USER: placeholder

kube2py:
  image:
    name: kube2py
    repository: zaavee/kube2py
    version: 2.0.0

  configs:
    EXTERNAL_ENDPOINT: "http://httpbin-api.mateapp.svc.cluster.local"
    PORT: "8080"
    APP_ENV: "testing-helm"

  secrets:
    password: placeholder
    login: placeholder
    external_endpoint: "http://httpbin-api.mateapp.svc.cluster.local"
    DB_CONNECTION: placeholder

  resources:
    requests:
      memory: "128Mi"
      cpu: "40m"
    limits:
      memory: "128Mi"
      cpu: "40m"

  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70
