name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  GITHUB_ACTIONS: Test env variable

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display GITHUB_ACTIONS env variable
        run: echo "GITHUB_ACTIONS has value ${{ env.GITHUB_ACTIONS }}"

      - name: Display name of the branch and repository
        run: echo "Name of the branch ${{ github.ref_name }} and name of repository ${{ github.repository }}"

      - name: Display the event that initiated the workflow
        run: echo "The workflow wat triggered by event ${{ github.event_name }}"

