name: python-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.13
  DOCKER_IMAGE_NAME: kube2py

jobs:
  python-ci:
    strategy:
      matrix:
        PythonVersion: [ 3.13, 3.12, 3.11 ]
        OsType: [ ubuntu-latest, windows-latest ]

    name: Python CI
    runs-on: ${{ matrix.OsType }}
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.PythonVersion }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.PythonVersion }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Check Complexity
        run: |
          cd ../
          flake8 . --statistics --max-complexity=10 --exit-zero

      - name: Run unit tests with pytest
        run: |
          pytest -v --cov=. --cov-report=term-missing --cov-report=json

      - name: Upload Python artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: .

      - name: Upload Helm artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts

  build-image:
    name: Build and push image
    needs:
      - python-ci
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Download Python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  helm-ci:
    name: Helm CI
    runs-on: ubuntu-latest
    needs:
      - python-ci
    if: github.ref_name == 'main'

    steps:
      - name: Download Helm artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Lint Helm
        run: |
          helm lint ./kube2py/

      - name: Template Helm
        run: |
          helm template kube2py ./kube2py/ -f ./kube2py/values.yaml

      - name: Package Helm
        run: |
          helm package ./kube2py

      - name: Upload Helm artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-package
          path: ./*.tgz

  deploy-helm-dev:
    name: Deploy Helm
    needs:
      - build-image
      - helm-ci
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      environment: development
      version: ${{ github.sha }}
    secrets: inherit

  deploy-helm-staging:
    name: Deploy Helm
    needs:
      - deploy-helm-dev
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      environment: staging
      version: ${{ github.sha }}
      helm-values-path: ./kube2py/values/staging.yml
      helm-release-name: kube2py-staging
    secrets: inherit
